language: clojure
jdk:
- oraclejdk8
script: lein test
before_deploy:
- echo $INIT_ENV >> ~/init.sh && chmod +x ~/init.sh && . ~/init.sh
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  on: heroku
notifications:
  email: false
sudo: false
