language: clojure
jdk:
- oraclejdk8
install:
- wget -O boot https://github.com/boot-clj/boot/releases/download/2.0.0-rc9/boot.sh
- chmod 755 boot
- ./boot -V
script: ./boot test
after_script:
- echo $INIT_ENV >> ~/init.sh && chmod +x ~/init.sh && . ~/init.sh
- ./boot deploy
notifications:
  email: false
sudo: false