# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:lein-2.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      BOOT_JVM_OPTIONS: "-Xmx2g -XX:MaxPermSize=128m"

    steps:
      - run: sudo bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"
      - run: boot -V

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: boot jar

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.boot" }}

      # run tests!
      - run: boot test
